# Generated by Django 5.2.2 on 2025-07-07 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='deadline',
            field=models.DateField(),
        ),
    ]
